# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: 'src/WebApp/vnetpocapp/vnetpocapp.sln'
    verbosityRestore: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: 'src/WebApp/vnetpocapp/vnetpocapp.sln'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish projects'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: Bash@3
  displayName: 'Migrations Bundle'  
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-ef
      dotnet ef migrations bundle --verbose --runtime win-x64 -p src/WebApp/vnetpocapp/vnetpocapp/vnetpocapp.csproj
      cp efbundle.exe ${BUILD_ARTIFACTSTAGINGDIRECTORY}/Infrastructure

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/Infratructure'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/Infrastructure'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: demoapp